// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cpp_rmse
arma::rowvec cpp_rmse(arma::mat x, arma::mat y, bool byband);
RcppExport SEXP _stfusion_cpp_rmse(SEXP xSEXP, SEXP ySEXP, SEXP bybandSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type byband(bybandSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rmse(x, y, byband));
    return rcpp_result_gen;
END_RCPP
}
// spatial_filtering
arma::mat spatial_filtering(arma::mat& f1, arma::mat& f2, arma::ivec& fdims, int& w, arma::vec& wg, int& nsim);
RcppExport SEXP _stfusion_spatial_filtering(SEXP f1SEXP, SEXP f2SEXP, SEXP fdimsSEXP, SEXP wSEXP, SEXP wgSEXP, SEXP nsimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type f1(f1SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type f2(f2SEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type fdims(fdimsSEXP);
    Rcpp::traits::input_parameter< int& >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type wg(wgSEXP);
    Rcpp::traits::input_parameter< int& >::type nsim(nsimSEXP);
    rcpp_result_gen = Rcpp::wrap(spatial_filtering(f1, f2, fdims, w, wg, nsim));
    return rcpp_result_gen;
END_RCPP
}
// sequ
arma::uvec sequ(int n);
RcppExport SEXP _stfusion_sequ(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(sequ(n));
    return rcpp_result_gen;
END_RCPP
}
// get_ngbs
arma::uvec get_ngbs(int i, int w, int nrow, int ncol);
RcppExport SEXP _stfusion_get_ngbs(SEXP iSEXP, SEXP wSEXP, SEXP nrowSEXP, SEXP ncolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    rcpp_result_gen = Rcpp::wrap(get_ngbs(i, w, nrow, ncol));
    return rcpp_result_gen;
END_RCPP
}
// ngb_dist
arma::vec ngb_dist(int i, arma::uvec inds, int nrow, int ncol);
RcppExport SEXP _stfusion_ngb_dist(SEXP iSEXP, SEXP indsSEXP, SEXP nrowSEXP, SEXP ncolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type inds(indsSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    rcpp_result_gen = Rcpp::wrap(ngb_dist(i, inds, nrow, ncol));
    return rcpp_result_gen;
END_RCPP
}
// distance_to_na
arma::vec distance_to_na(arma::vec& r, arma::ivec& dims, int maxdist);
RcppExport SEXP _stfusion_distance_to_na(SEXP rSEXP, SEXP dimsSEXP, SEXP maxdistSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type r(rSEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< int >::type maxdist(maxdistSEXP);
    rcpp_result_gen = Rcpp::wrap(distance_to_na(r, dims, maxdist));
    return rcpp_result_gen;
END_RCPP
}
// gaussian_kernel
arma::vec gaussian_kernel(arma::vec x, arma::vec y, double sigma);
RcppExport SEXP _stfusion_gaussian_kernel(SEXP xSEXP, SEXP ySEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussian_kernel(x, y, sigma));
    return rcpp_result_gen;
END_RCPP
}
// gaussian_filter
arma::vec gaussian_filter(int i, arma::uvec& inds, int nrow, int ncol, double sigma);
RcppExport SEXP _stfusion_gaussian_filter(SEXP iSEXP, SEXP indsSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type inds(indsSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussian_filter(i, inds, nrow, ncol, sigma));
    return rcpp_result_gen;
END_RCPP
}
// blur
arma::mat blur(arma::mat& r, arma::uvec& rdims, double sigma);
RcppExport SEXP _stfusion_blur(SEXP rSEXP, SEXP rdimsSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type r(rSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type rdims(rdimsSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(blur(r, rdims, sigma));
    return rcpp_result_gen;
END_RCPP
}
// unsharp_masking
arma::mat unsharp_masking(arma::mat& r, arma::uvec& rdims, double w);
RcppExport SEXP _stfusion_unsharp_masking(SEXP rSEXP, SEXP rdimsSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type r(rSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type rdims(rdimsSEXP);
    Rcpp::traits::input_parameter< double >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(unsharp_masking(r, rdims, w));
    return rcpp_result_gen;
END_RCPP
}
// complete_obs
arma::uvec complete_obs(arma::mat m, int dimn, int hard);
RcppExport SEXP _stfusion_complete_obs(SEXP mSEXP, SEXP dimnSEXP, SEXP hardSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type dimn(dimnSEXP);
    Rcpp::traits::input_parameter< int >::type hard(hardSEXP);
    rcpp_result_gen = Rcpp::wrap(complete_obs(m, dimn, hard));
    return rcpp_result_gen;
END_RCPP
}
// filter_nna
List filter_nna(arma::mat m);
RcppExport SEXP _stfusion_filter_nna(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(filter_nna(m));
    return rcpp_result_gen;
END_RCPP
}
// filter
int filter(arma::mat x, arma::vec y);
RcppExport SEXP _stfusion_filter(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(filter(x, y));
    return rcpp_result_gen;
END_RCPP
}
// local_regression
arma::mat local_regression(arma::mat& x, arma::mat& y, arma::ivec& cdims, int w);
RcppExport SEXP _stfusion_local_regression(SEXP xSEXP, SEXP ySEXP, SEXP cdimsSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type cdims(cdimsSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(local_regression(x, y, cdims, w));
    return rcpp_result_gen;
END_RCPP
}
// sp_pred
arma::mat sp_pred(arma::mat ref, arma::mat img, arma::uvec dims, int w, int nng);
RcppExport SEXP _stfusion_sp_pred(SEXP refSEXP, SEXP imgSEXP, SEXP dimsSEXP, SEXP wSEXP, SEXP nngSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type ref(refSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type img(imgSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type nng(nngSEXP);
    rcpp_result_gen = Rcpp::wrap(sp_pred(ref, img, dims, w, nng));
    return rcpp_result_gen;
END_RCPP
}
// sp_pred_par
arma::mat sp_pred_par(arma::mat ref, arma::mat img, arma::uvec dims, arma::uvec indx, int w, int nng);
RcppExport SEXP _stfusion_sp_pred_par(SEXP refSEXP, SEXP imgSEXP, SEXP dimsSEXP, SEXP indxSEXP, SEXP wSEXP, SEXP nngSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type ref(refSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type img(imgSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type indx(indxSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type nng(nngSEXP);
    rcpp_result_gen = Rcpp::wrap(sp_pred_par(ref, img, dims, indx, w, nng));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_stfusion_cpp_rmse", (DL_FUNC) &_stfusion_cpp_rmse, 3},
    {"_stfusion_spatial_filtering", (DL_FUNC) &_stfusion_spatial_filtering, 6},
    {"_stfusion_sequ", (DL_FUNC) &_stfusion_sequ, 1},
    {"_stfusion_get_ngbs", (DL_FUNC) &_stfusion_get_ngbs, 4},
    {"_stfusion_ngb_dist", (DL_FUNC) &_stfusion_ngb_dist, 4},
    {"_stfusion_distance_to_na", (DL_FUNC) &_stfusion_distance_to_na, 3},
    {"_stfusion_gaussian_kernel", (DL_FUNC) &_stfusion_gaussian_kernel, 3},
    {"_stfusion_gaussian_filter", (DL_FUNC) &_stfusion_gaussian_filter, 5},
    {"_stfusion_blur", (DL_FUNC) &_stfusion_blur, 3},
    {"_stfusion_unsharp_masking", (DL_FUNC) &_stfusion_unsharp_masking, 3},
    {"_stfusion_complete_obs", (DL_FUNC) &_stfusion_complete_obs, 3},
    {"_stfusion_filter_nna", (DL_FUNC) &_stfusion_filter_nna, 1},
    {"_stfusion_filter", (DL_FUNC) &_stfusion_filter, 2},
    {"_stfusion_local_regression", (DL_FUNC) &_stfusion_local_regression, 4},
    {"_stfusion_sp_pred", (DL_FUNC) &_stfusion_sp_pred, 5},
    {"_stfusion_sp_pred_par", (DL_FUNC) &_stfusion_sp_pred_par, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_stfusion(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
