# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

complete_obs <- function(m, dimn) {
    .Call(`_stfusion_complete_obs`, m, dimn)
}

cpp_rmse <- function(x, y, byband) {
    .Call(`_stfusion_cpp_rmse`, x, y, byband)
}

spatial_filtering <- function(f1, f2, fdims, w, wg, nsim) {
    .Call(`_stfusion_spatial_filtering`, f1, f2, fdims, w, wg, nsim)
}

get_fractures <- function(img, ctof, k) {
    .Call(`_stfusion_get_fractures`, img, ctof, k)
}

get_heterogeneity <- function(clss, w, nrow, ncol) {
    .Call(`_stfusion_get_heterogeneity`, clss, w, nrow, ncol)
}

classify_isodata <- function(img, K = 4L, I = 100L, P = 2L, maxStdv = 500, minDis = 500, minS = 200, M = 0.05, k = 4L) {
    .Call(`_stfusion_classify_isodata`, img, K, I, P, maxStdv, minDis, minS, M, k)
}

get_dist <- function(ind, ref, w, nrows, ncols) {
    .Call(`_stfusion_get_dist`, ind, ref, w, nrows, ncols)
}

fsdaf_spatial_filtering <- function(c1, c2, f1, delta, dims, w, nsim, nclass, minr, maxr) {
    .Call(`_stfusion_fsdaf_spatial_filtering`, c1, c2, f1, delta, dims, w, nsim, nclass, minr, maxr)
}

get_ngbs <- function(i, w, nrow, ncol) {
    .Call(`_stfusion_get_ngbs`, i, w, nrow, ncol)
}

#' @title Calculate radiometric parameters
#' 
#' @description Calculates the slope and intercept to radiometrically correct
#' satellite images.
#' 
#' @details the function has to be applied for each band independently. 
#' Matrices x and y must have the pixels as rows and different dates as
#' columns. Both matrices must have the same length and NAs are not
#' allowed.
#' 
#' @param x a matrix with the original image (pixels x dates)
#' @param y a matrix with the reference image (pixels x dates)
#' @param dims a vector with the dimensions of the image (rows x columns)
#' @param w a number specifying the window radius (side 2w+1)
#' 
#' @returns a matrix with pixels x parameters (slope and intercept)
#' 
radio_par <- function(x, y, dims, w) {
    .Call(`_stfusion_radio_par`, x, y, dims, w)
}

starfm_spatial_filter <- function(c1, c2, f1, dims, redb, nirb, w, ns) {
    .Call(`_stfusion_starfm_spatial_filter`, c1, c2, f1, dims, redb, nirb, w, ns)
}

apply_blur <- function(r, rdims, sigma) {
    .Call(`_stfusion_apply_blur`, r, rdims, sigma)
}

composite_genr <- function(x, n) {
    .Call(`_stfusion_composite_genr`, x, n)
}

composite_lois <- function(x, y, cdims, w) {
    .Call(`_stfusion_composite_lois`, x, y, cdims, w)
}

filter_cor <- function(x, y) {
    .Call(`_stfusion_filter_cor`, x, y)
}

filter_sin <- function(x, y) {
    .Call(`_stfusion_filter_sin`, x, y)
}

local_lm <- function(x, y, n, cdims, w) {
    .Call(`_stfusion_local_lm`, x, y, n, cdims, w)
}

spatial_filtering_par <- function(ref, img, dims, indx, w, nng, spwgt) {
    .Call(`_stfusion_spatial_filtering_par`, ref, img, dims, indx, w, nng, spwgt)
}

