# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

complete_obs <- function(m, dimn) {
    .Call(`_stfusion_complete_obs`, m, dimn)
}

cpp_rmse <- function(x, y, byband) {
    .Call(`_stfusion_cpp_rmse`, x, y, byband)
}

spatial_filtering <- function(f1, f2, fdims, w, wg, nsim) {
    .Call(`_stfusion_spatial_filtering`, f1, f2, fdims, w, wg, nsim)
}

get_ngbs <- function(i, w, nrow, ncol) {
    .Call(`_stfusion_get_ngbs`, i, w, nrow, ncol)
}

#' @title Calculate radiometric parameters
#' 
#' @description Calculates the slope and intercept to radiometrically correct
#' satellite images.
#' 
#' @details the function has to be applied for each band independently. 
#' Matrices x and y must have the pixels as rows and different dates as
#' columns. Both matrices must have the same length and NAs are not
#' allowed.
#' 
#' @param x a matrix with the original image (pixels x dates)
#' @param y a matrix with the reference image (pixels x dates)
#' @param dims a vector with the dimensions of the image (rows x columns)
#' @param w a number specifying the window radius (side 2w+1)
#' 
#' @returns a matrix with pixels x parameters (slope and intercept)
#' 
radio_par <- function(x, y, dims, w) {
    .Call(`_stfusion_radio_par`, x, y, dims, w)
}

apply_blur <- function(r, rdims, sigma) {
    .Call(`_stfusion_apply_blur`, r, rdims, sigma)
}

composite_genr <- function(x, n) {
    .Call(`_stfusion_composite_genr`, x, n)
}

composite_lois <- function(x, y, cdims, w) {
    .Call(`_stfusion_composite_lois`, x, y, cdims, w)
}

filter_cor <- function(x, y) {
    .Call(`_stfusion_filter_cor`, x, y)
}

filter_sin <- function(x, y) {
    .Call(`_stfusion_filter_sin`, x, y)
}

local_lm <- function(x, y, n, cdims, w) {
    .Call(`_stfusion_local_lm`, x, y, n, cdims, w)
}

spatial_filtering_par <- function(ref, img, dims, indx, w, nng, spwgt) {
    .Call(`_stfusion_spatial_filtering_par`, ref, img, dims, indx, w, nng, spwgt)
}

