# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gaussian_kernel <- function(x, y, sigma) {
    .Call(`_stfusion_gaussian_kernel`, x, y, sigma)
}

gaussian_filter <- function(i, inds, nrow, ncol, sigma) {
    .Call(`_stfusion_gaussian_filter`, i, inds, nrow, ncol, sigma)
}

unsharp_masking <- function(r, rdims, w) {
    .Call(`_stfusion_unsharp_masking`, r, rdims, w)
}

apply_blur <- function(r, rdims, sigma) {
    .Call(`_stfusion_apply_blur`, r, rdims, sigma)
}

cpp_rmse <- function(x, y, byband) {
    .Call(`_stfusion_cpp_rmse`, x, y, byband)
}

spatial_filtering <- function(f1, f2, fdims, w, wg, nsim) {
    .Call(`_stfusion_spatial_filtering`, f1, f2, fdims, w, wg, nsim)
}

get_ngbs <- function(i, w, nrow, ncol) {
    .Call(`_stfusion_get_ngbs`, i, w, nrow, ncol)
}

sequ <- function(n) {
    .Call(`_stfusion_sequ`, n)
}

ngb_dist <- function(i, inds, nrow, ncol) {
    .Call(`_stfusion_ngb_dist`, i, inds, nrow, ncol)
}

distance_to_na <- function(r, dims, maxdist) {
    .Call(`_stfusion_distance_to_na`, r, dims, maxdist)
}

complete_obs <- function(m, dimn, hard) {
    .Call(`_stfusion_complete_obs`, m, dimn, hard)
}

filter_nna <- function(m) {
    .Call(`_stfusion_filter_nna`, m)
}

filter <- function(x, y) {
    .Call(`_stfusion_filter`, x, y)
}

local_regression <- function(x, y, cdims, w) {
    .Call(`_stfusion_local_regression`, x, y, cdims, w)
}

sp_pred <- function(ref, img, dims, w, nng, spwgt) {
    .Call(`_stfusion_sp_pred`, ref, img, dims, w, nng, spwgt)
}

vclamp <- function(x, minx, maxx) {
    .Call(`_stfusion_vclamp`, x, minx, maxx)
}

sp_pred_par <- function(ref, img, dims, indx, w, nng, spwgt) {
    .Call(`_stfusion_sp_pred_par`, ref, img, dims, indx, w, nng, spwgt)
}

